version: '3.8'

services:
    server:
        image: node:latest
        container_name: server
        ports:
            - 8000:8000
        volumes:
            - ./nodejs-docker:/app
        working_dir: /app
        command: npm run dev
        restart: unless-stopped
        depends_on:
            - database

    database:
        image: mongo:latest
        container_name: database
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root